name: Update License Year
on:
  schedule:
    - cron: '0 0 1 1 *'
jobs:
  update-year:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update Year in License
      run: sed -i "s/Copyright © [0-9]\{4\}/Copyright © $(date +%Y)/" LICENSE.md
    - name: Commit and Push Changes if Any
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        # Check for changes
        if ! git diff --quiet; then
          git add .
          git commit -m "Update license year to $(date +%Y)"
          git push
        else
          echo "No changes to commit."
        fi
